# action.yml
name: 'OpenFaaS build and push'
description: 'Builds a docker image from your OpenFaaS function and pushes it to your registry'
branding:
  icon: upload-cloud
  color: blue
inputs:
  stack-file:
    description: 'The OpenFaaS function definition file'
    required: true
    default: 'stack.yml'
  docker-username:
    description: 'Your docker username with push authorization'
    required: true
  docker-password:
    description: 'Your docker password'
    required: true
  platforms:
    description: 'the platform abbreviations to build for, e. g. linux/amd64,linux/arm/v7'
    required: false
    default: 'linux/amd64'
outputs:
  tag:
    description: 'The image tag built'
runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    - ${{ inputs.stack-file }}
    - ${{ inputs.docker-username }}
    - ${{ inputs.docker-password }}
    - ${{ inputs.platforms }}