name: CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Determine Image
      run: |
        echo "::set-env name=IMAGE_NAME::$(echo "docker.pkg.github.com/${REPOSITORY}/action:${SHA}")"
        echo "${IMAGE_NAME}"
      env:
        REPOSITORY: ${{ github.repository }}
        SHA: ${{ github.sha	}}
    - name: Move tests to root folder, subfolders are not supported in uses
      run: |
        cp -Rf test/* .
    - name: Test building simple stack - setup
      id: build-simple
      uses: './'
      with:
        # The OpenFaaS function definition file
        stack-file: './simple.yml'
        # Your docker username with push authorization
        docker-username: ${{ secrets.DOCKER_USERNAME }}
        # Your docker username with push authorization
        docker-password: ${{ secrets.DOCKER_PASSWORD }}
        # the platform abbreviations to build for, e. g. linux/amd64,linux/arm/v7
        platforms: linux/amd64,linux/arm/v7
    - name: Test building multi-function stack - validate simple
      run: |
        export repo=mrsimpson/simple && \
        curl -H "Authorization: Bearer $(curl -sSL "https://auth.docker.io/token?service=registry.docker.io&scope=repository:${repo}:pull" | jq --raw-output .token)" "https://index.docker.io/v2/${repo}/manifests/${TAG}" | grep "fprocess=echo simple"
      env:
        TAG: ${{ steps.outputs.build-simple.tag }}
    - name: Test building multi-function stack - setup
      id: build-multi
      uses: './'
      with:
        # The OpenFaaS function definition file
        stack-file: './multi-function.yml'
        # Your docker username with push authorization
        docker-username: ${{ secrets.DOCKER_USERNAME }}
        # Your docker username with push authorization
        docker-password: ${{ secrets.DOCKER_PASSWORD }}
        # the platform abbreviations to build for, e. g. linux/amd64,linux/arm/v7
        platforms: linux/amd64
    - name: Test building multi-function stack - validate first
      run: |
        export repo=mrsimpson/unit-test-first && \
        curl -H "Authorization: Bearer $(curl -sSL "https://auth.docker.io/token?service=registry.docker.io&scope=repository:${repo}:pull" | jq --raw-output .token)" "https://index.docker.io/v2/${repo}/manifests/${TAG}" | grep "fprocess=echo first"
      env:
        TAG: ${{ steps.outputs.build-multi.tag }}
    - name: Test building multi-function stack - validate second
      run: |
        export repo=mrsimpson/unit-test-second && \
        curl -H "Authorization: Bearer $(curl -sSL "https://auth.docker.io/token?service=registry.docker.io&scope=repository:${repo}:pull" | jq --raw-output .token)" "https://index.docker.io/v2/${repo}/manifests/${TAG}" | grep "fprocess=echo second"
      env:
        TAG: ${{ steps.outputs.build-multi.tag }}
    - name: Build action image
      run: |
        docker build -t ${IMAGE_NAME} .
    - name: publish to github registry
      run: |
        docker login docker.pkg.github.com -u "${GITHUB_ACTOR}" -p "${GITHUB_TOKEN}" && \
        docker push "${IMAGE_NAME}"
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
